name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --all
    - name: Run tests
      run: cargo test --verbose --all
    - name: Install daimojo locally
      run: cargo install --path .
    - name: Execute libjustversion (must fail)
      run: daimojo --lib target/debug/libjustversion.so show || true
    - name: Execite libempty (must succeed)
      run: daimojo --lib target/debug/libempty.so show
